name: CI

on:
  push: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine
    env:
      SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
      DB_URI: ${{ secrets.DB_URI }}
      SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
      SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install .
  push-to-gcr:
    name: Build & Push to GCR
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}'
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: gcr.io
          project_id: ${{ secrets.PROJECT_ID }}
          image_name: spotiapp-backend
          image_tag: latest, ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: ./ 